# -*- mode: ruby -*-
# vi: set ft=ruby :

username = `whoami`.strip
total_cpus = `nproc`.to_i
cpus_per_vm = (total_cpus / 3.0).ceil

SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
  
    config.vm.box = "generic/ubuntu2004"
  config.vm.define "#{username}S" do |server|
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.cpus = cpus_per_vm
      vb.name = "#{username}S"
    end
    server.vm.hostname = "#{username}S"
    server.vm.synced_folder "./scripts", "/vagrant/scripts"
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provision "shell", privileged: true, path: "scripts/scripts.sh", args: ["server", SERVER_IP]
  end
end
