require 'etc'
total_cpus = Etc.nprocessors
cpus_per_vm = (total_cpus / 3.0).ceil

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "bhamdiS" do |server|
    server.vm.hostname = "bhamdiS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = cpus_per_vm
      vb.name = "bhamdiS"
    end

    server.vm.provision "shell", path: "./scripts.sh", args: "master"
  end

  config.vm.define "bhamdiSW" do |worker|
    worker.vm.hostname = "bhamdiSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = cpus_per_vm
      vb.name = "bhamdiSW"
    end

    worker.vm.provision "shell", path: "./scripts.sh", args: "worker"
  end
end
