apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-votrlogin-gitlab
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://gitlab.com//mettez-le-lien-vers-votre-repo-gitlab
    targetRevision: HEAD
    path: manifests
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true