apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-bhamdi-gitlab
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://gitlab.com/bhamdi/IOT-42
    targetRevision: HEAD
    path: manifests
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true